SeoSeungHwan/DIDA

presentation/src/main/java/com/dida/android/presentation/base/BaseFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/home/HomeFragment.kt

BaseFragment 에 navigate함수 추가하여 Fragment 중복시 발생하던 오류 checkNavigation으로 처리했던 것 수정하였습니다

feat. BaseFragment 에 navigate함수 추가

---

data/src/main/java/com/dida/data/di/RepositoryModule.kt
data/src/main/java/com/dida/data/repository/KlaytnRepositoryImpl.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/repository/KlaytnRepository.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/CreateUserAPI.kt
domain/src/main/java/com/dida/domain/usecase/CreateWalletAPI.kt
domain/src/main/java/com/dida/domain/usecase/HomeAPI.kt
domain/src/main/java/com/dida/domain/usecase/LoginAPI.kt
domain/src/main/java/com/dida/domain/usecase/NicknameCheckAPI.kt
domain/src/main/java/com/dida/domain/usecase/SendEmailAPI.kt
domain/src/main/java/com/dida/domain/usecase/SoldOutAPI.kt
presentation/src/main/java/com/dida/android/presentation/base/BaseFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/email/EmailFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/email/EmailViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/login/LoginMainFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/login/LoginMainViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/add/AddFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/add/AddPurposeFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/add/AddPurposeViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/add/AddViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/community/CommunityFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/defi/DefiViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/nav/home/HomeViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/nickname/NicknameFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/nickname/NicknameViewModel.kt

도메인 레이어에 있던 UseCase 모든 기능이 하나의 클래스에 들어가 있어서 각각 내용별로 분리하였습니다

fix. Domain레이어에 UseCase 관련하여 수정

---

.idea/misc.xml
presentation/src/main/java/com/dida/android/presentation/views/detailnft/DetailNftBindingAdapters.kt
presentation/src/main/java/com/dida/android/presentation/views/detailnft/DetailNftViewModel.kt
presentation/src/main/res/layout/fragment_detail_nft.xml
presentation/src/main/res/layout/skeleton_detail_nft.xml

feat. 상세페이지 스켈레톤뷰 재구현(강제로 딜레이 0.5초 부여)

---

.idea/misc.xml
data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/model/tradenft/PostBuyNftRequest.kt
data/src/main/java/com/dida/data/model/tradenft/PostSellNftRequest.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/SellNftAPI.kt

NFT판매등록 API 구현해놨습니다. (추후에 디자인나오면 API 호출)

feat. NFT 판매등록 API 구현

---

data/src/main/java/com/dida/data/shareperference/DataStorePreferences.kt
presentation/src/main/java/com/dida/android/util/MyFirebaseMessagingService.kt
presentation/src/main/java/com/dida/android/util/NotificationUtil.kt
presentation/src/main/res/values/strings.xml

feat. FCM Notification 구현 완료

---

presentation/src/main/java/com/dida/android/presentation/adapter/community/CreateCommunityNftAdapter.kt
presentation/src/main/java/com/dida/android/presentation/adapter/community/ReservationNFTRecyclerViewAdapter.kt
presentation/src/main/java/com/dida/android/presentation/adapter/detailnft/CommunityAdapter.kt
presentation/src/main/java/com/dida/android/presentation/adapter/home/CollectionAdapter.kt
presentation/src/main/java/com/dida/android/presentation/adapter/home/HotSellerAdapter.kt
presentation/src/main/java/com/dida/android/presentation/adapter/home/HotsAdapter.kt
presentation/src/main/java/com/dida/android/presentation/adapter/home/RecentNftAdapter.kt
presentation/src/main/java/com/dida/android/presentation/adapter/home/SoldOutAdapter.kt
presentation/src/main/res/layout/holder_collection.xml
presentation/src/main/res/layout/holder_community.xml
presentation/src/main/res/layout/holder_create_community_nft.xml
presentation/src/main/res/layout/holder_hots.xml
presentation/src/main/res/layout/holder_hotseller.xml
presentation/src/main/res/layout/holder_mypage_user_cards.xml
presentation/src/main/res/layout/holder_soldout.xml

1. RecyclerView Adapter 관련 클릭 이벤트 리팩토링 [0242028]

[DIDA] RecyclerView Adapter > Adapter 클릭 이벤트 리팩토링

---

.idea/markdown-navigator.xml
.idea/misc.xml
presentation/src/main/res/drawable-xxxhdpi/custom_surface2_bottom_radius12.xml
presentation/src/main/res/drawable-xxxhdpi/custom_surface2_radius12.xml
presentation/src/main/res/layout/fragment_home.xml
presentation/src/main/res/layout/skeleton_holder_hots.xml
presentation/src/main/res/layout/skeleton_holder_hotseller.xml
presentation/src/main/res/layout/skeleton_holder_soldout.xml

[DIDA] refactor. homeSkeletonView > 홈화면 스켈레톤뷰 디자인 수정

---

data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/interceptor/BearerInterceptor.kt

1. 재발급 토큰 Interceptor 405떨어지던 에러 수정 [76d1a46]

[DIDA] Interceptor > 토큰 재발급 로직 수정

---

data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/di/NetworkModule.kt
data/src/main/java/com/dida/data/mapper/Mapper.kt
data/src/main/java/com/dida/data/model/post/GetCardsPostResponse.kt
data/src/main/java/com/dida/data/model/userInfo/PutUserDescriptionRequest.kt
data/src/main/java/com/dida/data/model/userInfo/PutUserNicknameRequest.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/model/nav/post/CardPost.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/CardsPostLikeAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/CardsPostMyAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/UpdateProfileDescriptionAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/UpdateProfileNicknameAPI.kt
feature/create-community/src/main/java/com/dida/create_community/CreateCommunityViewModel.kt
feature/create-community/src/main/java/com/dida/create_community/adapter/CreateCommunityNftAdapter.kt
feature/create-community/src/main/res/layout/holder_create_community_nft.xml
feature/update-profile/src/main/java/com/dida/update/profile/UpdateProfileViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/CreateCommunityNftFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/UpdateProfileFragment.kt

1. 커뮤니티 생성 NFT선택 API 추가 [5294d58]
2. 커뮤니티 생성 NFT선택 API 연동 [0a8fc4f]

[DIDA] 커뮤니티 생성 NFT 선택

---

presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt

[DIDA] fix. NFT상세페이지 >. NFT상세페이지 이동 중 비정상종료되는 문제 해결

---

build-logic/convention/src/main/java/com/example/convention/AndroidCommonConventionPlugin.kt
build-logic/convention/src/main/java/com/example/convention/AndroidFeatureConventionPlugin.kt
build-logic/convention/src/main/java/com/example/convention/AndroidPresentationConventionPlugin.kt
common/src/main/java/com/dida/common/adapter/CommunityAdapter.kt
data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/NetworkResult.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/PostsAPI.kt
feature/community/src/main/java/com/dida/community/CommunityViewModel.kt
feature/community/src/main/java/com/dida/community/adapter/PostsPagingSource.kt
gradle/didalibs.versions.toml
presentation/src/main/java/com/dida/android/presentation/views/CommunityFragment.kt

1. 페이징 라이브러리 추가 [52e3fe3] [7ee5132]
2. PagingSource 추가 [9c12718] [4e10498]

[DIDA] 커뮤니티 페이징

---

build-logic/convention/src/main/java/com/example/convention/AndroidCommonConventionPlugin.kt
build-logic/convention/src/main/java/com/example/convention/AndroidFeatureConventionPlugin.kt
build-logic/convention/src/main/java/com/example/convention/AndroidPresentationConventionPlugin.kt
common/src/main/java/com/dida/common/adapter/CommunityAdapter.kt
common/src/main/java/com/dida/common/adapter/CommunityPagingAdapter.kt
data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/NetworkResult.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/PostsAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/PostsCardCardIdAPI.kt
feature/community/src/main/java/com/dida/community/CommunityViewModel.kt
feature/community/src/main/java/com/dida/community/adapter/PostsPagingSource.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftViewModel.kt
gradle/didalibs.versions.toml
presentation/src/main/java/com/dida/android/presentation/views/CommunityFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt

1. NFT상세 커뮤니티 API 추가 [d930d2f]
2. NFT상세 커뮤니티 API 연동 [9d06fec]

[DIDA] NFT 상세 화면 커뮤니티 내용

---

build-logic/convention/src/main/java/com/example/convention/AndroidCommonConventionPlugin.kt
build-logic/convention/src/main/java/com/example/convention/AndroidFeatureConventionPlugin.kt
build-logic/convention/src/main/java/com/example/convention/AndroidPresentationConventionPlugin.kt
common/src/main/java/com/dida/common/adapter/CommunityAdapter.kt
common/src/main/java/com/dida/common/adapter/CommunityPagingAdapter.kt
data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/mapper/Mapper.kt
data/src/main/java/com/dida/data/model/post/GetHotCardsResponse.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/NetworkResult.kt
domain/src/main/java/com/dida/domain/model/nav/community/ActiveNFTHolderModel.kt
domain/src/main/java/com/dida/domain/model/nav/community/HotCard.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/HotCardAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/PostsAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/PostsCardCardIdAPI.kt
feature/community/src/main/java/com/dida/community/CommunityNavigationAction.kt
feature/community/src/main/java/com/dida/community/CommunityViewModel.kt
feature/community/src/main/java/com/dida/community/HotCardActionHandler.kt
feature/community/src/main/java/com/dida/community/adapter/ActiveNFTRecyclerViewAdapter.kt
feature/community/src/main/java/com/dida/community/adapter/HotCardAdapter.kt
feature/community/src/main/java/com/dida/community/adapter/PostsPagingSource.kt
feature/community/src/main/res/layout/fragment_community.xml
feature/community/src/main/res/layout/holder_active_nft.xml
feature/community/src/main/res/layout/holder_hot_card.xml
feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftViewModel.kt
gradle/didalibs.versions.toml
presentation/src/main/java/com/dida/android/presentation/views/CommunityFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. 커뮤니티 > 시끌벅적 게시판 API 추가 [90aac23]
2. 커뮤니티 > 시끌벅적 게시판 API 연동 [8c60f56]

[DIDA] 커뮤니티 시끌벅적 게시판

---

data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/model/detail/GetDetailNFTResponse.kt
data/src/main/java/com/dida/data/model/post/PostPostCardIdRequest.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/model/nav/detailnft/DetailNFT.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/PostCardIdAPI.kt
feature/community/src/main/java/com/dida/community/adapter/PostsPagingSource.kt
feature/create-community-input/src/main/java/com/dida/create_community_input/CreateCommunityInputActionHandler.kt
feature/create-community-input/src/main/java/com/dida/create_community_input/CreateCommunityInputBindingAdapters.kt
feature/create-community-input/src/main/java/com/dida/create_community_input/CreateCommunityInputNavigationAction.kt
feature/create-community-input/src/main/java/com/dida/create_community_input/CreateCommunityInputViewModel.kt
feature/create-community-input/src/main/res/layout/fragment_create_community_input.xml
feature/create-community/src/main/java/com/dida/create_community/CreateCommunityActionHandler.kt
feature/create-community/src/main/java/com/dida/create_community/CreateCommunityNavigationAction.kt
feature/create-community/src/main/java/com/dida/create_community/CreateCommunityViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/CreateCommunityFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/CreateCommunityInputFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. 커뮤니티 생성 API 추가 [8f52166]
2. 커뮤니티 생성 기능 연동 [7bb0cb5]

[DIDA] 커뮤니티 생성

---

common/src/main/res/drawable/custom_brandlemon_fill_radius100.xml
common/src/main/res/layout/holder_community.xml
common/src/main/res/layout/holder_mypage_user_cards.xml
domain/src/main/java/com/dida/domain/model/nav/home/Hots.kt
feature/community-detail/src/main/res/layout/fragment_detail_community.xml
feature/home/src/main/res/layout/fragment_home.xml
feature/home/src/main/res/layout/holder_hots.xml

1. 홈 > Hot Item 관련 String 수정 [3828d32]

[DIDA] 홈 > Hot Item String 수정

---

build-logic/convention/src/main/java/com/example/convention/project/KotlinAndroid.kt
gradle/didalibs.versions.toml

Kotlin : 1.7.2
Compose : 1.3.2
ComposeMaterial : 1.3.0

[DIDA] fix. Compose > 코틀린 버전에 맞게 컴포즈 버전 수정

---

feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftViewModel.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/bottom/DetailNftBottomSheet.kt
feature/nft-detail/src/main/res/layout/fragment_detail_nft.xml
feature/password/src/main/java/com/dida/password/PasswordDialog.kt
feature/password/src/main/java/com/dida/password/PasswordViewModel.kt
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt

[[DIDA] fix NFT상세 > 로그인을 하지않았을 때 NFT상세 바텀메뉴 안뜨게 수정]

[DIDA] fix NFT상세 > 로그인을 하지않았을 때 NFT상세 바텀메뉴 안뜨게 수정

---

data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/mapper/Mapper.kt
data/src/main/java/com/dida/data/model/response/CardHideListResponse.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/model/nav/hide/CardHideListItem.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/HideCancelNftAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/HideListAPI.kt
domain/src/main/java/com/dida/domain/usecase/main/HideNftAPI.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftViewModel.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/bottom/DetailNftBottomSheet.kt
feature/nft-detail/src/main/res/layout/fragment_detail_nft.xml
feature/password/src/main/java/com/dida/password/PasswordDialog.kt
feature/password/src/main/java/com/dida/password/PasswordViewModel.kt
feature/settings/src/main/java/com/dida/settings/SettingsNavigationAction.kt
feature/settings/src/main/java/com/dida/settings/SettingsViewModel.kt
feature/settings/src/main/java/com/dida/settings/hidelist/HideListActionHandler.kt
feature/settings/src/main/java/com/dida/settings/hidelist/HideListAdapter.kt
feature/settings/src/main/java/com/dida/settings/hidelist/HideListBindingAdapter.kt
feature/settings/src/main/java/com/dida/settings/hidelist/HideListNavigationAction.kt
feature/settings/src/main/java/com/dida/settings/hidelist/HideListViewModel.kt
feature/settings/src/main/res/drawable/ic_hide_cancel.xml
feature/settings/src/main/res/layout/fragment_hide_list.xml
feature/settings/src/main/res/layout/holder_hide_list_item.xml
feature/settings/src/main/res/values/strings.xml
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/HideListFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/SettingsFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

구현 
- NFT 숨기기
- 숨기기 목록확인
- 숨기기 취소
추후 예정(서버 API수정 필요)
- NFT 숨기기 목록에서 유저 이름과 NFT가격정보 추가해야함

NFT숨기기 , 숨기기목록확인, 숨기기 취소 구현

---

data/src/main/java/com/dida/data/model/response/GetPostPostIdResponse.kt
domain/src/main/java/com/dida/domain/model/nav/post/Post.kt
feature/community-detail/src/main/java/com/dida/community_detail/DetailCommunityActionHandler.kt
feature/community-detail/src/main/java/com/dida/community_detail/DetailCommunityNavigationAction.kt
feature/community-detail/src/main/java/com/dida/community_detail/DetailCommunityViewModel.kt
feature/community-detail/src/main/res/layout/fragment_detail_community.xml
presentation/src/main/java/com/dida/android/presentation/views/DetailCommunityFragment.kt
presentation/src/main/res/navigation/navigation_graph.xml

1. [커뮤니티 상세 > 커뮤니티 상세 -> NFT상세 이동 로직 추가]

[DIDA] feat. 커뮤니티 상세 > 커뮤니티 상세 -> NFT상세 이동 로직 추가

---

build-logic/convention/src/main/java/com/example/convention/AndroidPresentationConventionPlugin.kt
build.gradle.kts
gradle/didalibs.versions.toml
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/dida/android/presentation/views/BaseFragment.kt

[DIDA] 에러 토스트 메시지 수정

---

common/src/main/java/com/dida/common/util/DecimalBindingAdatper.kt
common/src/main/res/layout/holder_community.xml
common/src/main/res/layout/holder_mypage_user_cards.xml
common/src/main/res/values/styles.xml
domain/src/main/java/com/dida/domain/model/nav/detailnft/Community.kt
domain/src/main/java/com/dida/domain/model/nav/home/Hots.kt
domain/src/main/java/com/dida/domain/model/nav/home/SoldOut.kt
domain/src/main/java/com/dida/domain/model/nav/mypage/BuySellList.kt
domain/src/main/java/com/dida/domain/model/nav/mypage/UserNft.kt
feature/home/src/main/res/layout/holder_hots.xml
feature/home/src/main/res/layout/holder_soldout.xml
feature/nft-detail/src/main/res/layout/fragment_detail_nft.xml
feature/nft-sale/src/main/java/com/dida/nft/sale/AddSaleNftBottomSheet.kt
feature/nft-sale/src/main/res/layout/bottom_add_sale_nft.xml
feature/settings/src/main/res/layout/holder_hide_list_item.xml
feature/wallet/src/main/res/layout/holder_wallet_nft_history.xml
model/src/main/java/com/dida/model/data/response/GetMainTermResponse.kt
model/src/main/java/com/dida/model/domain/Main.kt
model/src/main/java/com/dida/model/domain/MainTerm.kt
presentation/src/main/java/com/dida/android/presentation/views/SwapFragment.kt

- 스왑 : 소수점 6자리까지만 입력가능, 최대 Int자료형 Max까지만 입력가능
- NFT 가격 : 소수점 2자리까지만 입력가능 , 최대 Int자료형 Max까지만 입력가능
- NFT 가격 : 가격이 너무 길 경우  임시적으로 ...처리 (ellipsize사용)

NFT가격 및 스왑 코인수량에 대한 숫자Format 변경

---

common/src/main/java/com/dida/common/util/DecimalBindingAdatper.kt
common/src/main/res/layout/holder_community.xml
common/src/main/res/layout/holder_mypage_user_cards.xml
common/src/main/res/values/styles.xml
domain/src/main/java/com/dida/domain/model/nav/detailnft/Community.kt
domain/src/main/java/com/dida/domain/model/nav/home/Hots.kt
domain/src/main/java/com/dida/domain/model/nav/home/SoldOut.kt
domain/src/main/java/com/dida/domain/model/nav/mypage/BuySellList.kt
domain/src/main/java/com/dida/domain/model/nav/mypage/UserNft.kt
feature/home/src/main/res/layout/holder_hots.xml
feature/home/src/main/res/layout/holder_soldout.xml
feature/mypage/src/main/java/com/dida/mypage/MypageBindingAdapters.kt
feature/nft-detail/src/main/res/layout/fragment_detail_nft.xml
feature/nft-sale/src/main/java/com/dida/nft/sale/AddSaleNftBottomSheet.kt
feature/nft-sale/src/main/res/layout/bottom_add_sale_nft.xml
feature/settings/src/main/res/layout/holder_hide_list_item.xml
feature/user-profile/src/main/java/com/dida/user_profile/UserProfileBindingAdapters.kt
feature/wallet/src/main/res/layout/holder_wallet_nft_history.xml
model/src/main/java/com/dida/model/data/response/GetMainTermResponse.kt
model/src/main/java/com/dida/model/domain/Main.kt
model/src/main/java/com/dida/model/domain/MainTerm.kt
presentation/src/main/java/com/dida/android/presentation/views/SwapFragment.kt

fix. 팔로우,팔로잉 > 내 프로필, 다른사람 프로필에서 팔로우와 팔로잉 반대로 나오는 이슈해결

팔로우 팔로잉 반대로 나오는 이슈 해결

---

presentation/src/main/java/com/dida/android/presentation/views/SwapFragment.kt

스왑 코인수량 입력 시 바텀네비가 같이 올라가는 이슈 해결

스왑 코인수량 입력 시 바텀네비가 같이 올라가는 이슈 해결

---

data/src/main/java/com/dida/data/api/MainAPIService.kt
data/src/main/java/com/dida/data/mapper/Mapper.kt
data/src/main/java/com/dida/data/model/response/GetWalletAmountResponse.kt
data/src/main/java/com/dida/data/repository/MainRepositoryImpl.kt
domain/src/main/java/com/dida/domain/model/nav/swap/WalletAmount.kt
domain/src/main/java/com/dida/domain/repository/MainRepository.kt
domain/src/main/java/com/dida/domain/usecase/main/DeleteNftAPI.kt
feature/nft-detail/src/main/java/com/dida/nft_detail/DetailNftViewModel.kt
feature/wallet/src/main/java/com/dida/wallet/WalletViewModel.kt
feature/wallet/src/main/res/layout/fragment_wallet.xml
presentation/src/main/java/com/dida/android/presentation/views/DetailNftFragment.kt
presentation/src/main/java/com/dida/android/presentation/views/WalletFragment.kt

[DIDA] NFT삭제할 때 비밀번호 체크하는 로직 추가
